<a href="https://colab.research.google.com/github/golu628/Celebel/blob/main/gdp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/gdpWorld.csv')

In [3]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             227 non-null    object
 1   Region                              227 non-null    object
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          227 non-null    object
 5   Coastline (coast/area ratio)        227 non-null    object
 6   Net migration                       224 non-null    object
 7   Infant mortality (per 1000 births)  224 non-null    object
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object
 10  Phones (per 1000)                   223 non-null    object
 11  Arable (%)                          225 non-null    object
 12  Crops (%)                           225 non-null    object
 13  Other (%)                           225 non-null    object
 14  Climate                             205 non-null    object
 15  Birthrate                           224 non-null    object
 16  Deathrate                           223 non-null    object
 17  Agriculture                         212 non-null    object
 18  Industry                            211 non-null    object
 19  Service                             212 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 35.6+ KB

In [5]:
df.isnull().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [6]:
df.columns

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

In [7]:
for i in df:
  if df[i].dtype == 'object':
    print(i)

Country
Region
Pop. Density (per sq. mi.)
Coastline (coast/area ratio)
Net migration
Infant mortality (per 1000 births)
Literacy (%)
Phones (per 1000)
Arable (%)
Crops (%)
Other (%)
Climate
Birthrate
Deathrate
Agriculture
Industry
Service

In [8]:
for i in df:
  if df[i].dtype == 'object':
    df[i] = pd.to_numeric(df[i],errors = 'coerce')

In [26]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,NaN,NaN,31056997.0,647500.00,NaN,NaN,NaN,NaN,700.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,3581655.0,28748.00,NaN,NaN,NaN,NaN,4500.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,32930091.0,1097556.25,NaN,NaN,NaN,31.0,6000.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,57794.0,199.00,NaN,NaN,NaN,NaN,8000.0,NaN,NaN,10.0,0.0,75.0,2.0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,71201.0,468.00,NaN,NaN,NaN,NaN,19000.0,NaN,NaN,NaN,0.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             0 non-null      float64
 1   Region                              0 non-null      float64
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          0 non-null      float64
 5   Coastline (coast/area ratio)        0 non-null      float64
 6   Net migration                       63 non-null     float64
 7   Infant mortality (per 1000 births)  4 non-null      float64
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        0 non-null      float64
 10  Phones (per 1000)                   0 non-null      float64
 11  Arable (%)                          19 non-null     float64
 12  Crops (%)                           33 non-null     float64
 13  Other (%)                           19 non-null     float64
 14  Climate                             194 non-null    float64
 15  Birthrate                           5 non-null      float64
 16  Deathrate                           1 non-null      float64
 17  Agriculture                         1 non-null      float64
 18  Industry                            0 non-null      float64
 19  Service                             0 non-null      float64
dtypes: float64(18), int64(2)
memory usage: 35.6 KB

In [14]:
def outlier_thresholds(dataframe, col_name, q1=0.25, q3=0.75):
    quartile1 = dataframe[col_name].quantile(q1)
    quartile3 = dataframe[col_name].quantile(q3)
    interquantile_range = quartile3 - quartile1
    up_limit = quartile3 + 1.5 * interquantile_range
    low_limit = quartile1 - 1.5 * interquantile_range
    return low_limit, up_limit

In [22]:
for i in df.columns:
    low, up = outlier_thresholds(df, i)
    df[i] = np.where(df[i] > up, up, df[i])
    df[i] = np.where(df[i] < low, low, df[i])
    print("the outliers are", i, low, up)

the outliers are Country nan nan
the outliers are Region nan nan
the outliers are Population -25152598.75 43087995.25
the outliers are Area (sq. mi.) -651097.75 1097556.25
the outliers are Pop. Density (per sq. mi.) nan nan
the outliers are Coastline (coast/area ratio) nan nan
the outliers are Net migration 0.0 0.0
the outliers are Infant mortality (per 1000 births) -59.75 174.25
the outliers are GDP ($ per capita) -18800.0 36400.0
the outliers are Literacy (%) nan nan
the outliers are Phones (per 1000) nan nan
the outliers are Arable (%) -30.0 50.0
the outliers are Crops (%) 0.0 0.0
the outliers are Other (%) 37.5 137.5
the outliers are Climate 0.5 4.5
the outliers are Birthrate 8.5 28.5
the outliers are Deathrate 22.0 22.0
the outliers are Agriculture 0.0 0.0
the outliers are Industry nan nan
the outliers are Service nan nan

In [25]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,NaN,NaN,31056997.0,647500.00,NaN,NaN,NaN,NaN,700.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,3581655.0,28748.00,NaN,NaN,NaN,NaN,4500.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,32930091.0,1097556.25,NaN,NaN,NaN,31.0,6000.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,57794.0,199.00,NaN,NaN,NaN,NaN,8000.0,NaN,NaN,10.0,0.0,75.0,2.0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,71201.0,468.00,NaN,NaN,NaN,NaN,19000.0,NaN,NaN,NaN,0.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN